ahycoV3/ahycoV3/Controllers/ClanaksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ahycoV3.Models;
using System.IO;
using Microsoft.AspNet.Identity;
using PagedList;

namespace ahycoV3.Controllers
{
    public class ClanaksController : Controller
    {


        private ahycoV2Entities db = new ahycoV2Entities();

        // GET: Clanaks
        public ActionResult Index(string sortOrder, int? page, long? katId)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.UserSortParm = sortOrder == "User" ? "user_desc" : "User";
            var clanaks = (from b in db.Clanaks where b.kategorijaId == katId select b);

            switch (sortOrder)
            {
                case "name_desc":
                    clanaks = clanaks.OrderByDescending(s => s.naslovClanak);
                    break;
                case "Date":
                    clanaks = clanaks.OrderBy(s => s.datumClanak);
                    break;
                case "date_desc":
                    clanaks = clanaks.OrderByDescending(s => s.datumClanak);
                    break;
                case "User":
                    clanaks = clanaks.OrderBy(s => s.AspNetUser.Email);
                    break;
                case "user_desc":
                    clanaks = clanaks.OrderByDescending(s => s.AspNetUser.Email);
                    break;
                default:
                    clanaks = clanaks.OrderBy(s => s.naslovClanak);
                    break;
            }


            foreach (var clanak in clanaks)
            {
                string myString = clanak.sadrzajClanak.Substring(0, 200);
                int index = myString.LastIndexOf(' ');
                string outputString = myString.Substring(0, index);
                clanak.sadrzajClanak = outputString + "...";
            }
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            ViewBag.kategorijaId = katId;
            return View(clanaks.ToPagedList(pageNumber, pageSize));
        }



        // GET: Clanaks
        public ActionResult IndexUser(string sortOrder, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.UserSortParm = sortOrder == "User" ? "user_desc" : "User";

            var clanaks = from s in db.Clanaks.Include(c => c.AspNetUser).Include(c => c.Kategorije) select s;

            var CurrentUserId = User.Identity.GetUserId(); ;

            if (this.User.IsInRole("Editor"))
            {
                clanaks = (from b in db.Clanaks
                           where b.userId == CurrentUserId
                           select b);
            }

            switch (sortOrder)
            {
                case "name_desc":
                    clanaks = clanaks.OrderByDescending(s => s.naslovClanak);
                    break;
                case "Date":
                    clanaks = clanaks.OrderBy(s => s.datumClanak);
                    break;
                case "date_desc":
                    clanaks = clanaks.OrderByDescending(s => s.datumClanak);
                    break;
                case "User":
                    clanaks = clanaks.OrderBy(s => s.AspNetUser.Email);
                    break;
                case "user_desc":
                    clanaks = clanaks.OrderByDescending(s => s.AspNetUser.Email);
                    break;
                default:
                    clanaks = clanaks.OrderBy(s => s.naslovClanak);
                    break;
            }
            foreach (var clanak in clanaks)
            {
                string myString = clanak.sadrzajClanak.Substring(0, 200);
                int index = myString.LastIndexOf(' ');
                string outputString = myString.Substring(0, index);
                clanak.sadrzajClanak = outputString + "...";
            }
            int pageSize = 20;
            int pageNumber = (page ?? 1);
            return View(clanaks.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult PregledKategorija()
        {
            return View(db.Kategorijes.ToList());
        }

        public ActionResult PregledClanakaPoKategorijama(long katId)
        {
            var clanaks = from s in db.Clanaks select s;
            clanaks = (from b in db.Clanaks
                       where b.kategorijaId == katId
                       select b).Take(3);
            
            return PartialView("_prikazClanakaPoKat", clanaks.ToList());
        }

        // GET: Clanaks/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clanak clanak = db.Clanaks.Find(id);
            if (clanak == null)
            {
                return HttpNotFound();
            }
            ViewBag.istiUser = false;
            if (User.Identity.GetUserId() == clanak.AspNetUser.Id)
            {
                ViewBag.istiUser = true;
            }


            return View(clanak);
        }

        // GET: Clanaks/Create
        [Authorize(Roles = "Administrator, Editor")]
        public ActionResult Create()
        {
            ViewBag.userId = new SelectList(db.AspNetUsers, "Id", "Email");
            ViewBag.kategorijaId = new SelectList(db.Kategorijes, "kategorijaId", "nazivKategorija");
            return View();
        }

        // POST: Clanaks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Editor")]
        public ActionResult Create([Bind(Include = "clanakId,naslovClanak,sadrzajClanak,naslovnaClanak,datumClanak,kategorijaId,userId,uvodClanak")] Clanak clanak)
        {
            if (ModelState.IsValid)
            {
                byte[] imageData = null;
                if (Request.Files.Count > 0)
                {
                    HttpPostedFileBase poImgFile = Request.Files["ClanakNaslovna"];
                    using (var binary = new BinaryReader(poImgFile.InputStream))
                    {
                        imageData = binary.ReadBytes(poImgFile.ContentLength);
                        clanak.naslovnaClanak = imageData;
                    }
                }

                if (this.User.IsInRole("Editor"))
                {
                    clanak.userId = User.Identity.GetUserId();
                }

                db.Clanaks.Add(clanak);
                db.SaveChanges();
                return RedirectToAction("Details/" + clanak.clanakId.ToString());
            }
            ViewBag.userId = new SelectList(db.AspNetUsers, "Id", "Email", clanak.userId);
            ViewBag.kategorijaId = new SelectList(db.Kategorijes, "kategorijaId", "nazivKategorija", clanak.kategorijaId);
            return View(clanak);
        }

        // GET: Clanaks/Edit/5
        [Authorize(Roles = "Administrator, Editor")]
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clanak clanak = db.Clanaks.Find(id);
            if (clanak == null)
            {
                return HttpNotFound();
            }
            ViewBag.userId = new SelectList(db.AspNetUsers, "Id", "Email", clanak.userId);
            ViewBag.kategorijaId = new SelectList(db.Kategorijes, "kategorijaId", "nazivKategorija", clanak.kategorijaId);
            return View(clanak);
        }

        // POST: Clanaks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit([Bind(Include = "clanakId,naslovClanak,sadrzajClanak,naslovnaClanak,datumClanak,kategorijaId,userId,uvodClanak")] Clanak clanak)
        {

            if (ModelState.IsValid)
            {
                byte[] imageData = null;
                if (Request.Files["ClanakNaslovna"] != null)
                {
                    if (Request.Files.Count > 0)
                    {
                        HttpPostedFileBase poImgFile = Request.Files["ClanakNaslovna"];
                        using (var binary = new BinaryReader(poImgFile.InputStream))
                        {
                            imageData = binary.ReadBytes(poImgFile.ContentLength);
                            clanak.naslovnaClanak = imageData;
                        }
                    }
                }
                db.Entry(clanak).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("IndexUser");
            }
            ViewBag.userId = new SelectList(db.AspNetUsers, "Id", "Email", clanak.userId);
            ViewBag.kategorijaId = new SelectList(db.Kategorijes, "kategorijaId", "nazivKategorija", clanak.kategorijaId);
            return View(clanak);
        }

        // GET: Clanaks/Delete/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clanak clanak = db.Clanaks.Find(id);

ahycoV3/ahycoV3/Controllers/HomeController.cs
using ahycoV3.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ahycoV3.Controllers
{
    public class HomeController : Controller
    {
        private ahycoV2Entities db = new ahycoV2Entities();

        public ActionResult ClanakCarousel()
        {
            Clanak model = new Clanak();

            var clanaks = db.Clanaks.OrderByDescending(t => t.datumClanak).Take(3);
            foreach (var clanak in clanaks)
            {
                string myString = clanak.sadrzajClanak.Substring(0, 200);
                int index = myString.LastIndexOf(' ');
                string outputString = myString.Substring(0, index);
                clanak.sadrzajClanak = outputString + "...";
            }

            return PartialView("_carouselClanak", clanaks.ToList());
        }

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ReturnKategorije()
        {
            return PartialView("_naslovnaKategorije", db.Kategorijes.ToList());
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public FileContentResult UserPhotos()
        {
            if (User.Identity.IsAuthenticated)
            {
                String userId = User.Identity.GetUserId();

                if (userId == null)
                {
                    string fileName = HttpContext.Server.MapPath(@"~/Content/noImg.png");

                    byte[] imageData = null;
                    FileInfo fileInfo = new FileInfo(fileName);
                    long imageFileLength = fileInfo.Length;
                    FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read);
                    BinaryReader br = new BinaryReader(fs);
                    imageData = br.ReadBytes((int)imageFileLength);

                    return File(imageData, "image/png");

                }
                // to get the user details to load user Image
                var bdUsers = HttpContext.GetOwinContext().Get<ApplicationDbContext>();
                var userImage = bdUsers.Users.Where(x => x.Id == userId).FirstOrDefault();
                if (userImage.Slika == null)
                {
                    string fileName = HttpContext.Server.MapPath(@"~/Content/noImg.png");

                    byte[] imageData = null;
                    FileInfo fileInfo = new FileInfo(fileName);
                    long imageFileLength = fileInfo.Length;
                    FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read);
                    BinaryReader br = new BinaryReader(fs);
                    imageData = br.ReadBytes((int)imageFileLength);
                    return File(imageData, "image/png");
                }
                else
                {
                    return new FileContentResult(userImage.Slika, "image/jpeg");
                }
            }
            else
            {
                string fileName = HttpContext.Server.MapPath(@"~/Content/noImgG.png");

                byte[] imageData = null;
                FileInfo fileInfo = new FileInfo(fileName);
                long imageFileLength = fileInfo.Length;
                FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read);
                BinaryReader br = new BinaryReader(fs);
                imageData = br.ReadBytes((int)imageFileLength);
                return File(imageData, "image/png");

            }
        }
    }
}

ahycoV3/ahycoV3/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ahycoV3/ahycoV3/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ahycoV3/ahycoV3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "AHyCo";
}
<div class="naslovnaSlider">
    @Html.Action("ClanakCarousel", "Home")
</div>
<div class="col-xs-12 naslovSekcija">Kategorije članaka</div>
<div class="col-xs-12 sadrzajNaslovne clearfix">
    @Html.Action("ReturnKategorije", "Home")
</div>

ahycoV3/ahycoV3/Views/Home/_carouselClanak.cshtml
@model List<ahycoV3.Models.Clanak>

<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">

        @{
            var base64 = Convert.ToBase64String(Model.ElementAt(0).naslovnaClanak);
            var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
        }

        <div class="item active">
            <a href="@Url.Action("Details", "Clanaks", new { id = Model.ElementAt(0).clanakId }, null)">
                <img class="d-block img-fluid" src="@imgSrc" />
                <div class="carousel-caption">
                    <h3>@Html.DisplayFor(modelItem => Model.ElementAt(0).naslovClanak)</h3>
                    <p>@Html.Raw(Model.ElementAt(0).sadrzajClanak)</p>
                </div>
            </a>
        </div>

        @{
            base64 = Convert.ToBase64String(Model.ElementAt(1).naslovnaClanak);
            imgSrc = String.Format("data:image/gif;base64,{0}", base64);
        }

        <div class="item ">
            <a href="@Url.Action("Details", "Clanaks", new { id = Model.ElementAt(1).clanakId }, null)">
                <img src="@imgSrc" />
                <div class="carousel-caption">
                    <h3>@Html.DisplayFor(modelItem => Model.ElementAt(1).naslovClanak)</h3>
                    <p>@Html.Raw(Model.ElementAt(1).sadrzajClanak)</p>
                </div>
            </a>
</div>

        @{
            base64 = Convert.ToBase64String(Model.ElementAt(2).naslovnaClanak);
            imgSrc = String.Format("data:image/gif;base64,{0}", base64);
        }

        <div class="item ">
            <a href="@Url.Action("Details", "Clanaks", new { id = Model.ElementAt(2).clanakId }, null)">
                <img src="@imgSrc" />
                <div class="carousel-caption">
                    <h3>@Html.DisplayFor(modelItem => Model.ElementAt(2).naslovClanak)</h3>
                    <p>@Html.Raw(Model.ElementAt(2).sadrzajClanak)</p>
                </div>
            </a>
</div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

ahycoV3/ahycoV3/Views/Home/_naslovnaKategorije.cshtml
@model List<ahycoV3.Models.Kategorije>

<div class="sveKategorije col-xs-12 clearfix">

        @foreach (var item in Model)
        {
            var base64 = Convert.ToBase64String(item.slikaKategorija);
            var imgSrc = String.Format("data:image/gif;base64,{0}", base64);

            <div class="pojedinacnaKategorija col-xs-4">
                <a href="@Url.Action("Index", "Clanaks", new { katId = item.kategorijaId, katName = item.nazivKategorija}, null)">
                    <img class="kategorijaSlikaPozadina" src="@imgSrc" />
                    <div class="colorOverlay"></div>
                    <div class="naslovKategorije">
                        @Html.DisplayFor(modelItem => item.nazivKategorija)
                    </div>
                    <div class="opisKategorije">
                        @Html.Raw(item.opisKategorija)
                    </div>
                </a>
            </div>
        }
</div>